// ============================================================
// CAPTION TYPES - Frontend
// ============================================================

export type CaptionFormat = 'srt' | 'vtt' | 'ass' | 'ssa' | 'ttml' | 'json';
export type CaptionAlignment = 'left' | 'center' | 'right';
export type CaptionPosition = 'top' | 'middle' | 'bottom';
export type CaptionAnimation = 'none' | 'fade' | 'slide' | 'typewriter' | 'bounce';

export interface CaptionStyle {
  fontFamily: string;
  fontSize: number;
  fontColor: string;
  backgroundColor: string;
  backgroundOpacity: number;
  bold: boolean;
  italic: boolean;
  underline: boolean;
  alignment: CaptionAlignment;
  position: CaptionPosition;
  animation: CaptionAnimation;
  outlineColor?: string;
  outlineWidth?: number;
  shadowColor?: string;
  shadowOffset?: { x: number; y: number };
  padding: number;
  borderRadius: number;
}

export interface CaptionEntry {
  id: string;
  index: number;
  startTime: number;    // milliseconds
  endTime: number;      // milliseconds
  text: string;
  translatedText?: string;
  style?: Partial<CaptionStyle>;
  speaker?: string;
}

export interface Caption {
  id: string;
  videoId: string;
  language: string;
  languageCode: string;
  format: CaptionFormat;
  entries: CaptionEntry[];
  defaultStyle: CaptionStyle;
  createdAt: Date;
  updatedAt: Date;
  isAutoGenerated: boolean;
}

export interface CaptionGenerationRequest {
  videoId: string;
  videoUrl: string;
  language: string;
  targetLanguages?: string[];
  style?: Partial<CaptionStyle>;
  autoTranslate: boolean;
}

export interface CaptionGenerationResponse {
  captionId: string;
  entries: CaptionEntry[];
  format: CaptionFormat;
  downloadUrls: Record<CaptionFormat, string>;
}

export interface CaptionEditorState {
  caption: Caption | null;
  selectedEntryId: string | null;
  isEditing: boolean;
  currentTime: number;
  style: CaptionStyle;
  showPreview: boolean;
  isDirty: boolean;
}
