// ============================================================
// CAPTION EDITOR COMPONENT
// ============================================================

import React, { useState } from 'react';
import { useVideoStudioContext } from '../../context/VideoStudioContext';
import { captionGenerationService } from '../../services/captionGeneration.service';
import { downloadCaptions } from '../../utils/captionFormatter.util';
import { LanguageSelector } from './LanguageSelector';
import { LoadingSpinner } from '../Common/LoadingSpinner';
import { SUPPORTED_LANGUAGES } from '../../constants/languages';
import type { CaptionFormat, CaptionEntry } from '../../types/caption.types';

export function CaptionEditor() {
  const { project, captionState, updateCaptionState, addImportedVideo } = useVideoStudioContext();
  const [isGenerating, setIsGenerating] = useState(false);
  const [isBurning, setIsBurning] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [selectedFormat, setSelectedFormat] = useState<CaptionFormat>('srt');
  const selectedVideo = project.videos.find(v => v.id === project.selectedVideoId);

  const generateCaptions = async () => {
    if (!selectedVideo) return;
    setIsGenerating(true);
    try {
      const res = await captionGenerationService.generateCaptions({
        videoId: selectedVideo.id,
        videoUrl: selectedVideo.url,
        language: project.language,
        autoTranslate: false,
      });
      updateCaptionState({
        caption: {
          id: res.captionId,
          videoId: selectedVideo.id,
          language: project.language,
          languageCode: project.language,
          format: selectedFormat,
          entries: res.entries,
          defaultStyle: captionState.style,
          createdAt: new Date(),
          updatedAt: new Date(),
          isAutoGenerated: true,
        },
        isDirty: false,
      });
    } catch (err) {
      console.error('Caption generation failed:', err);
    } finally {
      setIsGenerating(false);
    }
  };

  const updateEntry = (id: string, text: string) => {
    if (!captionState.caption) return;
    updateCaptionState({
      caption: {
        ...captionState.caption,
        entries: captionState.caption.entries.map(e =>
          e.id === id ? { ...e, text } : e
        ),
      },
      isDirty: true,
    });
  };

  const handleExport = async () => {
    if (!captionState.caption) return;
    const content = await captionGenerationService.exportCaptions(captionState.caption, selectedFormat);
    downloadCaptions(content, `captions.${selectedFormat}`, selectedFormat);
  };

  const createManualCaption = () => {
    if (!selectedVideo) return;
    const now = new Date();
    updateCaptionState({
      caption: {
        id: crypto.randomUUID(), videoId: selectedVideo.id, language: project.language,
        languageCode: project.language, format: selectedFormat,
        entries: [{ id: crypto.randomUUID(), index: 0, startTime: 0, endTime: Math.max(1000, selectedVideo.duration * 1000), text: 'Caption text edit karein' }],
        defaultStyle: captionState.style, createdAt: now, updatedAt: now, isAutoGenerated: false,
      },
      isDirty: true,
    });
  };

  const burnCaptions = async () => {
    if (!selectedVideo || !captionState.caption) return;
    setIsBurning(true); setError(null);
    try {
      const result = await captionGenerationService.burnCaptions(selectedVideo.id, captionState.caption.entries, captionState.style);
      addImportedVideo({
        id: result.outputId, url: result.url, thumbnailUrl: selectedVideo.thumbnailUrl ?? '', duration: selectedVideo.duration,
        format: 'mp4', quality: selectedVideo.quality, aspectRatio: selectedVideo.aspectRatio, fileSize: 0, filename: 'Captioned video',
      });
    } catch (cause) { setError(cause instanceof Error ? cause.message : 'Caption burn fail ho gaya.'); }
    finally { setIsBurning(false); }
  };

  const FORMATS: CaptionFormat[] = ['srt', 'vtt', 'ass', 'json'];

  if (!selectedVideo) {
    return (
      <div style={{ textAlign: 'center', padding: '32px', color: 'var(--vs-text-muted)', fontSize: '14px' }}>
        Generate a video first to add captions.
      </div>
    );
  }

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '20px' }}>

      {/* Generate button */}
      {!captionState.caption && (
        <div style={{ textAlign: 'center', padding: '24px', background: 'var(--vs-bg-elevated)', borderRadius: '10px', border: '1px dashed var(--vs-border)' }}>
          <p style={{ margin: '0 0 16px', color: 'var(--vs-text-secondary)', fontSize: '14px' }}>
            Auto-generate captions from your video using AI speech recognition.
          </p>
          <button onClick={generateCaptions} disabled={isGenerating}
            style={{ padding: '10px 24px', background: 'var(--vs-primary)', border: 'none', borderRadius: '8px', color: '#fff', fontSize: '14px', fontWeight: 500, cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '8px', margin: '0 auto' }}>
            {isGenerating ? <><LoadingSpinner size="sm" /> Generating Captions...</> : '🎤 Auto-Generate Captions'}
          </button>
          <button onClick={createManualCaption}
            style={{ margin: '10px auto 0', padding: '8px 18px', background: 'var(--vs-bg-card)', border: '1px solid var(--vs-border)', borderRadius: '8px', color: 'var(--vs-text-primary)', cursor: 'pointer' }}>
            ✍️ Manual Caption Add Karo
          </button>
        </div>
      )}

      {/* Style controls */}
      {captionState.caption && (
        <>
          <div style={{ background: 'var(--vs-bg-elevated)', borderRadius: '10px', padding: '16px', display: 'flex', flexDirection: 'column', gap: '12px' }}>
            <h4 style={{ margin: 0, fontSize: '13px', fontWeight: 600, color: 'var(--vs-text-secondary)', textTransform: 'uppercase' }}>Caption Style</h4>
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '10px' }}>
              <label style={{ fontSize: '12px', color: 'var(--vs-text-muted)' }}>
                Font Size
                <input type="number" min={12} max={60} value={captionState.style.fontSize}
                  onChange={e => updateCaptionState({ style: { ...captionState.style, fontSize: Number(e.target.value) } })}
                  style={{ display: 'block', width: '100%', background: 'var(--vs-bg-card)', border: '1px solid var(--vs-border)', borderRadius: '4px', padding: '4px 8px', color: 'var(--vs-text-primary)', fontSize: '13px', marginTop: '4px' }} />
              </label>
              <label style={{ fontSize: '12px', color: 'var(--vs-text-muted)' }}>
                Position
                <select value={captionState.style.position}
                  onChange={e => updateCaptionState({ style: { ...captionState.style, position: e.target.value as 'top' | 'middle' | 'bottom' } })}
                  style={{ display: 'block', width: '100%', background: 'var(--vs-bg-card)', border: '1px solid var(--vs-border)', borderRadius: '4px', padding: '4px 8px', color: 'var(--vs-text-primary)', fontSize: '13px', marginTop: '4px' }}>
                  <option value="top">Top</option>
                  <option value="middle">Middle</option>
                  <option value="bottom">Bottom</option>
                </select>
              </label>
              <label style={{ fontSize: '12px', color: 'var(--vs-text-muted)', display: 'flex', alignItems: 'center', gap: '6px' }}>
                <input type="checkbox" checked={captionState.style.bold}
                  onChange={e => updateCaptionState({ style: { ...captionState.style, bold: e.target.checked } })} />
                Bold
              </label>
              <label style={{ fontSize: '12px', color: 'var(--vs-text-muted)', display: 'flex', alignItems: 'center', gap: '6px' }}>
                <input type="checkbox" checked={captionState.style.italic}
                  onChange={e => updateCaptionState({ style: { ...captionState.style, italic: e.target.checked } })} />
                Italic
              </label>
            </div>
          </div>

          {/* Caption entries */}
          <div>
            <h4 style={{ margin: '0 0 10px', fontSize: '13px', fontWeight: 600, color: 'var(--vs-text-secondary)', textTransform: 'uppercase' }}>
              Caption Entries ({captionState.caption.entries.length})
            </h4>
            <div style={{ maxHeight: '300px', overflowY: 'auto', display: 'flex', flexDirection: 'column', gap: '6px' }}>
              {captionState.caption.entries.map(entry => (
                <div key={entry.id} style={{
                  background: 'var(--vs-bg-elevated)', borderRadius: '6px', padding: '8px 10px',
                  border: `1px solid ${captionState.selectedEntryId === entry.id ? 'var(--vs-primary)' : 'var(--vs-border)'}`,
                  cursor: 'pointer',
                }} onClick={() => updateCaptionState({ selectedEntryId: entry.id })}>
                  <div style={{ fontSize: '10px', color: 'var(--vs-text-muted)', marginBottom: '4px' }}>
                    {Math.floor(entry.startTime / 1000)}s → {Math.floor(entry.endTime / 1000)}s
                  </div>
                  {captionState.selectedEntryId === entry.id ? (
                    <textarea value={entry.text}
                      onChange={e => updateEntry(entry.id, e.target.value)}
                      style={{ width: '100%', boxSizing: 'border-box', background: 'var(--vs-bg-primary)', border: '1px solid var(--vs-border)', borderRadius: '4px', color: 'var(--vs-text-primary)', padding: '4px', fontSize: '13px', fontFamily: 'inherit', resize: 'vertical' }}
                    />
                  ) : (
                    <p style={{ margin: 0, fontSize: '13px', color: 'var(--vs-text-primary)' }}>{entry.text}</p>
                  )}
                </div>
              ))}
            </div>
          </div>

          {/* Export */}
          <div style={{ display: 'flex', gap: '8px', alignItems: 'center' }}>
            <div style={{ display: 'flex', gap: '4px' }}>
              {FORMATS.map(f => (
                <button key={f}
                  onClick={() => setSelectedFormat(f)}
                  style={{ padding: '6px 12px', fontSize: '12px', border: '1px solid var(--vs-border)', borderRadius: '4px', cursor: 'pointer', background: selectedFormat === f ? 'var(--vs-primary)' : 'var(--vs-bg-elevated)', color: selectedFormat === f ? '#fff' : 'var(--vs-text-secondary)' }}>
                  {f.toUpperCase()}
                </button>
              ))}
            </div>
            <button onClick={handleExport}
              style={{ flex: 1, padding: '8px 16px', background: 'var(--vs-success)', border: 'none', borderRadius: '8px', color: '#fff', fontSize: '13px', fontWeight: 500, cursor: 'pointer' }}>
              ⬇ Export Captions
            </button>
            <button onClick={burnCaptions} disabled={isBurning}
              style={{ flex: 1, padding: '8px 16px', background: 'var(--vs-primary)', border: 'none', borderRadius: '8px', color: '#fff', fontSize: '13px', fontWeight: 500, cursor: 'pointer' }}>
              {isBurning ? 'Burning...' : '🔥 Burn Into Video'}
            </button>
          </div>
          {error && <p style={{ color: 'var(--text-danger)', margin: 0 }}>⚠️ {error}</p>}
        </>
      )}
    </div>
  );
}
